config/routes.rb
Eventsys::Application.routes.draw do
  resources :events, :only => [:index, :show]
  resources :comments, :only => :index

  resources :categories, :only => :index do
    resources :pictures, :only => [:index,:show], :path => "" do
      resources :comments, :only => :create
    end
  end

  devise_for :users
  get '/pictures', :to => 'pictures#all_pic', :as => :all_pic
  get '/like/:id', :to => 'pictures#like', :as => :like
  root :to => redirect('/categories')
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :pictures, :dependent => :destroy
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :picture, :counter_cache => true
  default_scope order("created_at DESC")
  validates :message,:user_id,:picture_id, :presence => true
end

app/models/event.rb
class Event < ActiveRecord::Base
  serialize :body
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :picture, :counter_cache => true
  validates :user_id, :uniqueness => {:scope => :picture_id}
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :category
  has_many :comments, :dependent => :destroy
  has_many :likes, :dependent => :destroy
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "128x128>" }
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :trackable, :validatable
  has_many :comments, :dependent => :destroy
  has_many :likes, :dependent => :destroy

  attr_accessible :email, :password, :password_confirmation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
  before_filter :best_pic

  def best_pic
    @best_picture ||= Picture.order("likes_count DESC").first.image(:medium)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.includes([:picture,:user]).all
  end

  def create
    pic = Picture.find_by_id(params[:picture_id])
    current_user.comments.create(:picture => pic, :message => params[:comment][:message])
    redirect_to :back
  end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.group(:user)
  end

  def show
    @name = params[:id]
    @user = params[:user]
    @event = Event.where("name = ? and user =? ",@name, @user)
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_filter :find_picture, :only => [:show, :like]

  def index
    @pictures = Picture.includes(:category).where("categories.title = ? ", params[:category_id]).paginate(:page => params[:page])
  end

  def all_pic
    @pictures = Picture.order("likes_count DESC").paginate(:page => params[:page])
  end

  def like
    like = @picture.likes.build(:user_id => current_user.id)
    flash[:error] = "Error" unless like.save
    redirect_to :back
  end

  private

  def find_picture
    @picture = Picture.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/categories/index.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first.active= link_to "Current", categories_path
  .content
    %h2.title
      = t("web-app-theme.all", :default => "All")
      Categories
    .inner
      %table.table
        %tr
          %th.first ID
          %th
            = t("activerecord.attributes.category.title", :default => t("activerecord.labels.title", :default => "Title"))
          %th= t("web-app-theme.created_at", :default => "Created at")
          %th.last &nbsp;
        - @categories.each do |category|
          %tr{:class => cycle("odd", "even")}
            %td
              = category.id
            %td
              = category.title
            %td
              = category.created_at.to_s(:short)
            %td.last
              = link_to "#{t("web-app-theme.show", :default => "Show")}", category_pictures_path(category.title)
      .actions-bar.wat-cf
        .actions

app/views/comments/index.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.active= link_to "Comments", "#"
  .content
    .inner
      %br
      - @comments.each do |comment|
        #footer
          .block{:style => "background-color: gray;"}
            %p{:style => "background-color: gray;"}
              %strong
                = "#{comment.user.email} said:"
              = comment.message

app/views/events/index.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first.active= link_to "Current", events_path
  .content
    %h2.title
      All Events
    .inner
      %table.table
        %tr
          %th.first User
          %th navigation
          %th sign in
          %th sign out
          %th comments
          %th likes
          %th.last &nbsp;
        - @events.each do |e|
          %tr{:class => cycle("odd", "even")}
            %td= e.user
            - %w(user-navigation user-sign_in user-sign_out comment-added like-added).each do |name|
              %td= link_to "Show", event_path(name, :user => e.user)
            %td.last
      .actions-bar.wat-cf
        .actions

app/views/events/show.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first.first= link_to "Back", events_path
      %li.first.active= link_to "Current", "#"
  .content
    %h2.title
      = @user
      = "- >"
      = @name
    .inner
      %table.table
        %tr
          %th.first ID
          %th Name
          %th Body
          %th.last created_at
        - @event.each do |e|
          %tr{:class => cycle("odd", "even")}
            %td= e.id
            %td= e.name
            %td= e.body
            %td.last= e.created_at.to_s(:short)
      .actions-bar.wat-cf
        .actions

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Event system
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tag
  %body
    #container
      #header
        %h1
          %a{:href => "/"} Event system
        #user-navigation
          %ul.wat-cf
            %li
              = link_to "Logout", destroy_user_session_path, :method => :delete, :class => "logout"
        #main-navigation
          %ul.wat-cf
            %li
              = link_to "Categories", categories_path
            %li
              = link_to "Pictures", all_pic_path
            %li
              = link_to "Comments", comments_path
            %li
              = link_to "Events", events_path

      #wrapper.wat-cf
        .flash
          - flash.each do |type, message|
            %div{:class => "message #{type}"}
              %p= message
        #main
          = yield
          #footer
            .block
              %p
                Copyright &copy; #{Time.now.year} Event system.
        #sidebar
          = render(:partial => 'shared/sidebar')

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %title Web App
    = stylesheet_link_tag "application"
    = csrf_meta_tag
  %body
    #container
      #box
        = yield

app/views/layouts/sign.html.haml
!!!
%html
  %head
    %title Web App
    = stylesheet_link_tag "application"
    = csrf_meta_tag
  %body
    #container
      #box
        = yield

app/views/pictures/all_pic.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.active= link_to "Current", all_pic_path
  .content
    .inner
      .content
        .inner
          %br
          - @pictures.each do |pic|
            = link_to category_picture_path(pic.category.title, pic.id) do
              %div{:style => "float:left;margin-right: 30px"}
                %p= "Like: #{pic.likes_count.to_i}"
                %p= "Comments: #{pic.comments_count.to_i}"
                %p= image_tag pic.image(:thumb)
          .clear
      = will_paginate @pictures
      .clear

app/views/pictures/index.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "Back", categories_path
      %li.active= link_to "Current", category_pictures_path
  .content
    .inner
      .content
        .inner
          %br
          - @pictures.each do |pic|
            = link_to category_picture_path(pic.category.title, pic.id) do
              %div{:style => "float:left;margin-right: 30px"}
                %p= "Like: #{pic.likes_count.to_i}"
                %p= "Comments: #{pic.comments_count.to_i}"
                %p= image_tag pic.image(:thumb)
          .clear
      = will_paginate @pictures
      .clear

app/views/pictures/show.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "Back", category_pictures_path(@picture.category.title)
      %li.active= link_to "Current", category_picture_path
  .content
    .inner
      .content
        .inner
          %br
          %center
            = image_tag(@picture.image)
            .clear
            %br
            = link_to "Like", like_path(@picture.id), :class => "button", :style => "float: none; display:inline"
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "Comments", "#"
  .content
    .inner
      = form_for :comment, :url => category_picture_comments_path(@picture.category.title, @picture.id) do |f|
        %p
          = f.text_area :message, :style => "width: 100%; height:100px"
        %p
          = f.submit "Save"
  .content
    .inner
      - @picture.comments.includes(:user).each do |comment|
        #footer
          .block{:style => "background-color: gray;"}
            %p{:style => "background-color: gray;"}
              %strong
                = "#{comment.user.email} said:"
              = comment.message

app/views/shared/_sidebar.html.haml
.block.notice
  %h3 Best Picture
  .content
    %center
      %br
      = image_tag(@best_picture)